### ISSUE TITLE
Alternative diffusion network choice

### ISSUE THREAD

**Issue by stas-polukeev** [yileijin/Bootstrap-3D-GS#1]
Hi! 
First of all great idea and thank for your research!
I was thinking about impoving spatial consistency in generated views too and I wonder, have you thought of using Zero123 instead of SD? It has some embedded understanding of the scene, however, it needs to be integrated a little differently, as it takes the angle of the new view you want to see of the input image. May be you have some thoughts on this
Thanks in advance!

**Comment by yileijin** [comment]
Zeros123 aims to handle single objects rather than the entire scene so that its alignment issues may be even bigger than the original SD in our scenarios. On top of that, there are newly advanced Diffusion Models but we did not implement them, because we just wanted to demonstrate the effectiveness of improved training sampling, the results were just good enough. Furthermore, spatial consistency comes from the completeness of the provided training sets or the "learning and creating" ability of the model's structure, our work is to improve the training sets. So if you want to discuss this further with me, you can send me an email with more detail. yilei.jin123@gmail.com
